const ADMIN_PERMISSSION = {
    ADMIN_ADD: "ADMIN_ADD",
    ADD_PRODUCT: "ADD_PRODUCT",
    BOOK_VIEW: "BOOK_VIEW",
    // product
    PRODUCT_VIEW: "PRODUCT_VIEW",
    PRODUCT_CREATE: "PRODUCT_CREATE",
    ADMIN_VIEW: "ADMIN_VIEW",
    // category
    CATEGORY_VIEW: "CATEGORY_VIEW",
    CATEGORY_CREATE: "CATEGORY_CREATE",
};

export default ADMIN_PERMISSSION;
